### ISSUE TITLE
save_openid in OpenID controller

### ISSUE THREAD

**Issue by SET001** [badsyntax/kohana3-examples#1]
Regarding to OpenID controller in action_finish method: 
$user = ORM::factory('user')->save_openid($openid);
i got following error:
Invalid method save_openid called in Model_User
And after i checked in user model i do not found save_openid method. I can't find it anywhere. So what is it?

**Comment by badsyntax** [comment]
Hi. I'm using a base module to store all my generic models to allow model <a href="http://kohanaframework.org/guide/kohana/extension">transparent class extension.</a>

You can have a look here to view my base user model: https://github.com/badsyntax/kohana3-base/blob/master/classes/model/base/user.php

Scroll to the bottom of the class and you'll find the save_openid() definition. 

As you can see the method is really quite simple, it uses the user's openid ID for the username, email and openid_id columns. It's been a while since I put this code together, but if I remember correctly it wasn't possible to reliably get the user's email through the openid transaction process. This is just an example implementation and certainly needs some work, but the basics are there!

**Comment by SET001** [comment]
thanx
